# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddae99ae2a5e52fcac70b20db47b385b3405cfae6f44d55d4566310e7136feb1b125a8c9206e26b8ce0db54d1b4dd75469e4f228ac2901ffab5cc1f7b088bf65

test:
  secret_key_base: ac66385ff4501d3e47942b3b85bd4ea7a99f04b9da7751d816e9cf14d42f913dcb6602effdb49c73074a9b74d0cf863be5db670ccbcc09a86a40de7911dbe102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
